name: Build All

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # 5.5.0
      with:
        go-version: '>=1.21.0'
    - run: go version
    - name: Windows Build
      run: |
        $Env:GOOS='windows'
        go build -o GoReSym.exe
        Compress-Archive -DestinationPath GoReSym-windows.zip -LiteralPath ./GoReSym.exe -CompressionLevel Fastest
        Remove-Item ./GoReSym.exe
    - name: Linux Build
      run: |
        $Env:GOOS='linux'
        go build -o GoReSym
        Compress-Archive -DestinationPath GoReSym-linux.zip -LiteralPath ./GoReSym -CompressionLevel Fastest
        Remove-Item ./GoReSym
    - name: Mac Build
      run: |
        $Env:GOOS='darwin'
        go build -o GoReSym
        Compress-Archive -DestinationPath GoReSym-mac.zip -LiteralPath ./GoReSym -CompressionLevel Fastest
        Remove-Item ./GoReSym
    - name: Release Windows
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # 2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: GoReSym-windows.zip
    - name: Release Linux
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # 2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: GoReSym-linux.zip
    - name: Release Mac
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # 2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: GoReSym-mac.zip

